- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Allow ssh
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow HTTPS
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: Allow k3s API
  community.general.ufw:
    rule: allow
    port: "6443"
    proto: tcp

- name: Allow kubelet
  community.general.ufw:
    rule: allow
    port: "10250"
    proto: tcp

- name: Allow Flannel VXLAN
  community.general.ufw:
    rule: allow
    port: "8472"
    proto: udp

- name: Set ufw default policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }
    - { direction: routed, policy: deny }

- name: Enable ufw
  community.general.ufw:
    state: enabled
