apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    persistence:
      enabled: true
      name: data
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /data

    certResolvers:
      letsencrypt:
        email: {{ traefik_acme_email }}
        storage: /data/acme.json
        httpChallenge:
          entryPoint: web

    additionalArguments:
      - "--certificatesresolvers.default.acme.email={{ traefik_acme_email }}"
      - "--certificatesresolvers.default.acme.storage=/data/acme.json"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
    ports:
      web:
        exposedPort: 80
      websecure:
        exposedPort: 443
