name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Check with yamllint and ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Install linters
        run: pip install yamllint ansible-lint

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: ansible-lint
